sudo: required
language: cpp
compiler: gcc
dist: trusty
notifications:
    email: false

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
    - sudo apt-get update -q
    - sudo apt-get install -qq qt510base 
    - source /opt/qt510/bin/qt510-env.sh

script:
    - cd test
    - mkdir build
    - cd build
    - qmake "QMAKE_CC = gcc-5" ../
    - make
    - ./libdap-qt-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

